export const QUERY_KEYS = {
    // Account related keys
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    CREATE_BUSINESS: 'CREATE_BUSINESS',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    GET_ACCOUNT_AUTHORIZATION: 'GET_ACCOUNT_AUTHORIZATION',
    GET_ACCOUNT_DETAILS: 'GET_ACCOUNT_DETAILS',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    CHECK_ACCOUNT_EXISTS: 'CHECK_ACCOUNT_EXISTS',
    RESET_PASSWORD: 'RESET_PASSWORD',
    VERIFY_OTP: 'VERIFY_OTP',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    GET_ACTIVE_BUSINESS: 'GET_ACTIVE_BUSINESS',

    // Auth
    LOGIN: 'LOGIN',

    // Business
    UPDATE_BUSINESS: 'UPDATE_BUSINESS',
    CREATE_BUSINESS_TABLE: 'CREATE_BUSINESS_TABLE',
    GET_ALL_BUSINESS_TABLES: 'GET_ALL_BUSINESS_TABLES',
    CREATE_SERVICE_POINT: 'CREATE_SERVICE_POINT',
    UPDATE_SERVICE_POINT: 'UPDATE_SERVICE_POINT',
    GET_ALL_SERVICE_POINTS: 'GET_ALL_SERVICE_POINTS',
    GET_BUSINESS_DETAILS: 'GET_BUSINESS_DETAILS',

    // Upload
    UPLOAD_IMAGE: 'UPLOAD_IMAGE',

    // Menu
    CREATE_MENU_GROUP: 'CREATE_MENU_GROUP',
    GET_ALL_MENU_GROUPS: 'GET_ALL_MENU_GROUPS',
    CREATE_MENU_CATEGORY: 'CREATE_MENU_CATEGORY',
    GET_ALL_MENU_CATEGORIES: 'GET_ALL_MENU_CATEGORIES',
    GET_MENU_GROUP_CATEGORIES: 'GET_MENU_GROUP_CATEGORIES',
    CREATE_MENU_ITEM: 'CREATE_MENU_ITEM',
    GET_ALL_MENU_ITEMS: 'GET_ALL_MENU_ITEMS',
    GET_MENU_GROUP_ITEMS: 'GET_MENU_GROUP_ITEMS',
    GET_MENU_CATEGORY_ITEMS: 'GET_MENU_CATEGORY_ITEMS',

    // Staff
    CREATE_STAFF: 'CREATE_STAFF',
    GET_ALL_STAFF: 'GET_ALL_STAFF',

    // Legacy keys
    GET_USER: 'GET_USER',

    // ADD MORE KEYS AS NEEDED
}