export const QUERY_KEYS = {
    // Account related keys
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    CREATE_BUSINESS: 'CREATE_BUSINESS',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    GET_ACCOUNT_AUTHORIZATION: 'GET_ACCOUNT_AUTHORIZATION',
    GET_ACCOUNT_DETAILS: 'GET_ACCOUNT_DETAILS',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    CHECK_ACCOUNT_EXISTS: 'CHECK_ACCOUNT_EXISTS',
    RESET_PASSWORD: 'RESET_PASSWORD',
    VERIFY_OTP: 'VERIFY_OTP',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    
    // Legacy keys
    GET_USER: 'GET_USER',

    // ADD MORE KEYS AS NEEDED
}